### ISSUE TITLE
ERROR:Daemon:connection problem - is your daemon running?  Retrying occasionally...

### ISSUE THREAD

**Issue by useramuser** [lukechilds/docker-electrumx#1]
Hi, I tried a lot of stuff now to get this running.

I have bitcoind installed, synced, reindexed and want to run electrumx on the same server.
Everytime I try to run the docker command it seems to spin up the server and then just forever say 

ERROR:Daemon:connection problem - is your daemon running?  Retrying occasionally...

So it can somehow not connect to bitcoind, right?

I have configured a rpc user and password there and included this in the docker commands variables. 
I am running the docker command like this:

`docker run   -v /mnt/bitcoinserver2/electrumx:/data   -e DAEMON_URL=http://coindancer:ucjcjgtnlrnchhtlnkbudvrjljckb+@127.0.0.1   -e COIN=BitcoinSegwit   -p 50002:50002   elec:stream`

(elec:stream are the name and tag of the image that I built. It also does not work with lukechilds/electrumx)

**Comment by lukechilds** [comment]
Have you tested http://coindancer:ucjcjgtnlrnchhtlnkbudvrjljckb+@46.101.242.237 separately to see if you can access it?

**Comment by useramuser** [comment]
Yes, I guess, when I 
curl http://coindancer:ucjcjgtnlrnchhtlnkbudvrjljckb+@46.101.242.237:8333
I get
curl: (52) Empty reply from server

For all the other ports I get something like 
curl http://coindancer:ucjcjgtnlrnchhtlnkbudvrjljckb+@46.101.242.237
curl: (7) Failed to connect to 46.101.242.237 port 80: Connection refused

So I assumed the Empty reply was already somehow a positive reply. Is that true?

**Comment by useramuser** [comment]
Oh, In the beginning I forgot to add the port.
Now I do: 
docker run -v /mnt/bitcoinserver2/electrumx:/data -e DAEMON_URL=http://coindancer:ucjcjgtnlrnchhtlnkbudvrjljckb+@46.101.242.237:8333 -e COIN=BitcoinSegwit -p 50002:50002 elec:stream
And I get:
ERROR:Daemon:disconnected.  Retrying occasionally...
ERROR:Daemon:disconnected.  Retrying occasionally...

**Comment by useramuser** [comment]
Bitcoind is running and I currently have 32 connections.

Here is the output from bitcoin-cli getblockchaininfo
{
  "chain": "main",
  "blocks": 498401,
  "headers": 498401,
  "bestblockhash": "0000000000000000008883eda4c7908ebb5d419703866ee14b6ab2e88658c65d",
  "difficulty": 1590896927258.079,
  "mediantime": 1512823607,
  "verificationprogress": 0.9999992581486629,
  "chainwork": "000000000000000000000000000000000000000000c49313e02d8635339e1cdc",
  "pruned": false,
  "softforks": [
    {
      "id": "bip34",
      "version": 2,
      "reject": {
        "status": true
      }
    },
    {
      "id": "bip66",
      "version": 3,
      "reject": {
        "status": true
      }
    },
    {
      "id": "bip65",
      "version": 4,
      "reject": {
        "status": true
      }
    }
  ],
  "bip9_softforks": {
    "csv": {
      "status": "active",
      "startTime": 1462060800,
      "timeout": 1493596800,
      "since": 419328
    },
    "segwit": {
      "status": "active",
      "startTime": 1479168000,
      "timeout": 1510704000,
      "since": 481824
    }
  }
}

**Comment by useramuser** [comment]
So now:
curl --data-binary '{"jsonrpc":"1.0","id":"curltext","method":"getinfo","params":[]}' -H 'content-type:text/plain;' http://coindancer:ucjcjgtnlrnchhtlnkbudvrjljckb+@127.0.0.1:8332/

Gives the following reply:
{"result":{"deprecation-warning":"WARNING: getinfo is deprecated and will be fully removed in 0.16. Projects should transition to using getblockchaininfo, getnetworkinfo, and getwalletinfo before upgrading to 0.16","version":150100,"protocolversion":70015,"walletversion":139900,"balance":0.00000000,"blocks":498405,"timeoffset":-1,"connections":10,"proxy":"","difficulty":1590896927258.079,"testnet":false,"keypoololdest":1512353719,"keypoolsize":2000,"paytxfee":0.00000000,"relayfee":0.00001000,"errors":""},"error":null,"id":"curltext"}

That means connection works.

docker run -v /mnt/bitcoinserver2/electrumx:/data -e DAEMON_URL=http://coindancer:ucjcjgtnlrnchhtlnkbudvrjljckb+@127.0.0.1:8332/ -e COIN=BitcoinSegwit -p 50002:50002 elec:stream

gives still this reply:
INFO:root:ElectrumX server starting
INFO:Controller:event loop policy: None
INFO:Daemon:daemon #1 at 127.0.0.1:8332/ (current)
INFO:BlockProcessor:switching current directory to /data
INFO:BlockProcessor:using leveldb for DB backend
INFO:BlockProcessor:opened DB for serving
INFO:BlockProcessor:closing DB to re-open for sync
INFO:BlockProcessor:opened DB for sync
INFO:BlockProcessor:software version: ElectrumX 1.2.1
INFO:BlockProcessor:DB version: 6
INFO:BlockProcessor:coin: BitcoinSegwit
INFO:BlockProcessor:network: mainnet
INFO:BlockProcessor:height: -1
INFO:BlockProcessor:tip: 0000000000000000000000000000000000000000000000000000000000000000
INFO:BlockProcessor:tx count: 0
INFO:BlockProcessor:flush count: 0
INFO:BlockProcessor:sync time so far: 00s
INFO:BlockProcessor:reorg limit is 200 blocks
INFO:BlockProcessor:flushing DB cache at 1,200 MB
INFO:PeerManager:accepted new peer 1/13 btc.smsys.me from coins.py
INFO:PeerManager:accepted new peer 2/13 E-X.not.fyi from coins.py
INFO:PeerManager:accepted new peer 3/13 elec.luggs.co from coins.py
INFO:PeerManager:accepted new peer 4/13 electrum.vom-stausee.de from coins.py
INFO:PeerManager:accepted new peer 5/13 electrum3.hachre.de from coins.py
INFO:PeerManager:accepted new peer 6/13 electrum.hsmiths.com from coins.py
INFO:PeerManager:accepted new peer 7/13 erbium1.sytes.net from coins.py
INFO:PeerManager:accepted new peer 8/13 helicarrier.bauerj.eu from coins.py
INFO:PeerManager:accepted new peer 9/13 hsmiths4fyqlw5xw.onion from coins.py
INFO:PeerManager:accepted new peer 10/13 luggscoqbymhvnkp.onion from coins.py
INFO:PeerManager:accepted new peer 11/13 ozahtqwp25chjdjd.onion from coins.py
INFO:PeerManager:accepted new peer 12/13 us11.einfachmalnettsein.de from coins.py
INFO:PeerManager:accepted new peer 13/13 ELEX01.blackpole.online from coins.py
INFO:Controller:RPC server listening on localhost:8000
ERROR:Daemon:connection problem - is your daemon running?  Retrying occasionally...

**Comment by lukechilds** [comment]
You've edited your original comment so it now says you're connecting to `172.0.0.1`. That's going to loop back to the container, not the host, which is probably not what you want to do.

**Comment by useramuser** [comment]
Yes you where right. It was a bitcoind port issue.
I tried it short time now with `rpcallowip=0.0.0.0/0` and now electrum finally connects!! :-)
I have to figure out now the right setting for the bitcoind conf, so only my electrumx container can connect to the host.
Thanks!

**Comment by lukechilds** [comment]
No problem, glad you got it sorted. You may find it easier to manage if you dockerise `bitcoind` and manage access with docker-compose.

Vertcoin example: https://github.com/lukechilds/docker-electrum-vertcoin/blob/master/docker-compose.yml

**Comment by maxvint** [comment]
Try to add `--network host` when start docker.
