### ISSUE TITLE
Trouble with choice electrumx version via docker run

### ISSUE THREAD

**Issue by barbariska108** [lukechilds/docker-electrumx#13]
`docker run   -v /home/username/electrumx:/data   -e DAEMON_URL=http://InsAPI:BClo001Z43IIq@127.0.0.1:8332 -e RPC_HOST=127.0.0.1   -e COIN=BitcoinSegwit   -p 50002:50002 --net=host   lukechilds/electrumx:1.8`

`Unable to find image 'lukechilds/electrumx:1.8' locally
docker: Error response from daemon: manifest for lukechilds/electrumx:1.8 not found.`

I need to use the lastest version electrumX server

Version on docker image:

`INFO:BlockProcessor:software version: ElectrumX 1.4
INFO:BlockProcessor:supported protocol versions: 0.9-1.2
`

**Comment by barbariska108** [comment]
I update docker image to 1.8 version, can I make a pull request with a new version?

**Comment by lukechilds** [comment]
I've updated the Docker image with 1.8.x and 1.9.x versions, you can view the available tags here: https://cloud.docker.com/repository/docker/lukechilds/electrumx/tags
