### ISSUE TITLE
My error running docker run command

### ISSUE THREAD

**Issue by s3ton** [lukechilds/docker-electrumx#14]
Hi,
first time using docker and I think I did a mistake.
What I did was running the command:
`sudo docker run --net=host -v /media/user/hd/electrumx/data -e ..........`
basically I skipped the` :` after electrumx 
no wonder why my data folder is empty...
Do you know where am I saving all the data right now? is there a default directory?
I see that electrumx is syncing and saving data on my ssd but I don't know where.
Thanks for the help

**Comment by lukechilds** [comment]
Possibly inside the container? Have you checked the directory `/media/user/hd/electrumx/data` on the host to see if it exists?

Either way, this isn't an issue with the container.

I'd suggest just restart with the correct options.
