### ISSUE TITLE
ERROR:ElectrumX:[0] reading banner file /home/user/banner.txt: FileNotFoundError(2, 'No such file or directory')

### ISSUE THREAD

**Issue by s3ton** [lukechilds/docker-electrumx#15]
Everything is working now except for the banner file.
this is what I type:
`sudo docker run --net=host -v /media/user/hd/electrumx/data:/data -e DAEMON_URL="username:password@127.0.0.1:8332" -e BANNER_FILE="/home/user/banner.txt" -e REPORT_HOST_TOR="address.onion" -e COIN=BitcoinSegwit -p 50002:50002 lukechilds/electrumx:v1.8.7`
and the error I get is `ERROR:ElectrumX:[0]` reading banner file /home/user/banner.txt: FileNotFoundError(2, 'No such file or directory')`
but I'm pretty sure the file is there.
Thanks for the help!

**Comment by s3ton** [comment]
Ok I solved the issue by changing the command to:
ocker run --net=host -v /media/user/hd/electrumx/data:/data -v /home/user/banner.txt:/banner.txt -e DAEMON_URL="username:password@127.0.0.1:8332" -e BANNER_FILE=/banner.txt -e REPORT_HOST_TOR="address.onion" -e COIN=BitcoinSegwit -p 50002:50002 lukechilds/electrumx:v1.8.7

**Comment by lukechilds** [comment]
Yes, you were passing the path to the banner on your host to ElectrumX running inside the container.
