### ISSUE TITLE
Question: Can't connect ElectrumX to Bitcoind

### ISSUE THREAD

**Issue by MyNameIsOka** [lukechilds/docker-electrumx#16]
Hi all,

I want to build 2 containers which separately contain bitcoind and Electrumx and connect ElectrumX to bitcoind. 
Currently trying this on Regtest.

The bitcoind node is running and I can communicate via bitcoin-cli and curl commands
`curl --user U:P --data '{"method": "getinfo"}' http://127.0.0.1:5000`

When starting the ElectrumX container, after quite some time a Daemon connection error appears:
![image](https://user-images.githubusercontent.com/18796117/53293485-e3dfa980-3817-11e9-8a8b-140614050a91.png)

I used this command to start the ElectrumX container:
`docker run \
  -v ~/Documents/Crypto/AndGo/regtest02/data:/electrumx/data \
  -e DAEMON_URL=http://U:P@[IP address of bitcoind container]:18443 \
  -e COIN=BitcoinSegwit \
  -e NET=regtest \
  -e RPC_HOST=127.0.0.1 \
  -e RPC_PORT=18443 \
  -e HOST=electrumx \
  -p 50002:50002 \
  lukechilds/electrumx
`

I am still quite new to all this so I am not sure what to look into.
In bicoin.conf I set:
`rpcallowip=0.0.0.0/0`
`regtest.rpcport=18443`

Your help is much appreciated!

- Fabian

**Comment by lukechilds** [comment]
My docker compose config for Vertcoin + Electrum may help you:

https://github.com/lukechilds/docker-electrum-vertcoin/blob/master/docker-compose.yml

Should be almost identical for Bitcoin.

**Comment by MyNameIsOka** [comment]
Thank you for the quick response!
I ran the electrumx server via docker-compose now and it is connecting.
I still wonder, why it didn't work with the `docker run` command?
As I see it, the only difference was that with `docker run` I used the docker IP address while with docker-compose I used the service (?) name.

**Comment by lukechilds** [comment]
Likely a networking issue. You might be connecting back to local ports inside the the docker container rather than local ports on your host.

I'd recommend just sticking with docker-compose, it makes network configuration very simple.

**Comment by MyNameIsOka** [comment]
Alright, thank you for the help!
