### ISSUE TITLE
Any chance of an upgrade to 1.10? Pre-tipping to butter up dev ;-)

### ISSUE THREAD

**Issue by th3geek** [lukechilds/docker-electrumx#17]
Hi there!

I know your busy, but its more important than ever to upgrade your electrumx server because of the massive phishing attack. I like your new tip page. I've pre-tipped you $20 with more to follow the updated docker ;)

Your the best!

**Comment by lukechilds** [comment]
Thanks for the tip, I really appreciate it.

Working on this now, got the Docker image updated but having some issues with the Docker Hub automated build pipeline.

If you're building from source then v1.10.0 is live now in master.

If you're pulling the images from Docker Hub then I should have v1.10.0 up shortly.

**Comment by lukechilds** [comment]
All live on Docker Hub 🎉

Run this to update:

```
docker pull lukechilds/electrumx
```

**Comment by th3geek** [comment]
Yay!! thank you so much!  Check your pockets again ;)

**Comment by lukechilds** [comment]
@th3geek Thanks!
