### ISSUE TITLE
error while building on tinkerboard ( arm 32 )

### ISSUE THREAD

**Issue by panagiotos** [lukechilds/docker-electrumx#38]
Worked on amd64 systems but not on arm32. docker installed correctly.
Log of the build command `docker build -t electrumx_img .`

<img width="1423" alt="Screenshot 2019-09-21 at 1 24 28 AM" src="https://user-images.githubusercontent.com/46250897/65492693-01204780-decf-11e9-8f30-4547b6c22a9b.png">

**Comment by panagiotos** [comment]
After removing `rocksdb-dev` and `python-rocksdb` it build successfully.

**Comment by lukechilds** [comment]
Thanks for reporting your solution.

Related: https://github.com/lukechilds/docker-electrumx/pull/35
