### ISSUE TITLE
Integration with BTCPay Server - Please help on that PR

### ISSUE THREAD

**Issue by maltokyo** [lukechilds/docker-electrumx#41]
I have ElectrumX running nicely in docker using the full bitcoin node of BTCPay Server.  Works well.  I have submitted PR here:
https://github.com/btcpayserver/btcpayserver-docker/pull/217

In case you see some improvements or polishing possible, please let me know.

**Comment by maltokyo** [comment]
@lukechilds just to give you a heads up, this is pretty close to being accepted over at https://github.com/btcpayserver/btcpayserver-docker/pull/217
I hope all is ok for you.

**Comment by lukechilds** [comment]
@maltokyo great work!

I left some feedback on the other PR: https://github.com/btcpayserver/btcpayserver-docker/pull/217#issuecomment-550320822

**Comment by lukechilds** [comment]
Closing this issue as PR is now merged.

**Comment by maltokyo** [comment]
Thank you for your help!
