### ISSUE TITLE
What database does this Docker use by default?

### ISSUE THREAD

**Issue by debuggor** [lukechilds/docker-electrumx#45]
What database does Docker use by default?
rocksdb? leveled?
thanks

**Comment by debuggor** [comment]
if use leveldb, how can i set it to rocksdb?

**Comment by Mave95** [comment]
add the following param to your docker run

> -e DB_ENGINE=rocksdb

**Comment by debuggor** [comment]
thanks

**Comment by lukechilds** [comment]
Thanks @Mave95 

@debuggor We don't do anything special with the configuration, all the available ENV options are documented in the ElectrumX docs, you can see the `DB_ENGINE` option here: https://electrumx.readthedocs.io/en/latest/environment.html#envvar-DB_ENGINE

>What database does Docker use by default?

Same as above, we just use the default ElectrumX options, so currently as you already seem to be aware, it defaults to `leveldb`. If ElectrumX defaults to `rocksdb` in the future, so will this Docker image.
