### ISSUE TITLE
"Warning: Lowered maximum sessions from 1,000 to 674 because your open file limit is 1,024"

### ISSUE THREAD

**Issue by JamesCropcho** [lukechilds/docker-electrumx#5]
Hello,

Thanks for a great Docker image.

Upon startup I see the following in the logs:

```
WARNING lowered maximum sessions from 1,000 to 674 because your open file limit is 1,024  [util.py:60]
```

This brings to mind, from ElectrumX (https://github.com/kyuupichan/electrumx/blob/master/docs/HOWTO.rst#process-limits):

> You must ensure the ElectrumX process has a large open file limit. During sync it should not need more than about 1,024 open files. When serving it will use approximately 256 for LevelDB plus the number of incoming connections. It is not unusual to have 1,000 to 2,000 connections being served, so I suggest you set your open files limit to at least 2,500.
> 
> Note that setting the limit in your shell does NOT affect ElectrumX unless you are invoking ElectrumX directly from your shell. If you are using :command:`systemd`, you need to set it in the :file:`.service` file (see contrib/systemd/electrumx.service).

1) Is there a specific way anyone else here has raised that limit for themselves?
1) Would this be considered a bug? If so, would it be easily fixable nearly universally, and therefore a good candidate for a pull request?

Thanks,
James

**Comment by JamesCropcho** [comment]
Hello all,

I seem (?) to have fixed this, by appending to `docker run` the argument `--ulimit nofile=5120:5120`.

The error is no longer in the logs. Does this seem like a sane fix?


Thanks,
James

**Comment by lukechilds** [comment]
Hi, thanks for your updating with your solution.

Yes, setting the ulimit via a Docker flag is the correct solution.

Would happily accept a PR to the readme explaining some users may need to use this flags for high traffic nodes.
