### ISSUE TITLE
Plans to update to latest ElectrumX version?

### ISSUE THREAD

**Issue by maltokyo** [lukechilds/docker-electrumx#52]
Please let me know, Ill attempt to do on my own if you have no time.  Thank you!

**Comment by mzarglis** [comment]
I forked and created created and updated the version to 1.14.0 until they update the image here
(https://hub.docker.com/repository/docker/mzarglis/electrumx)

**Comment by maltokyo** [comment]
Great. Thank you!

**Comment by lukechilds** [comment]
Apologies for the delay, had some personal things going on and haven't been around a computer.

Merged https://github.com/lukechilds/docker-electrumx/pull/51 and pushed latest images to Docker Hub.
