### ISSUE TITLE
ERROR:electrumx:ElectrumX server terminated abnormally

### ISSUE THREAD

**Issue by UbuntuEvangelist** [lukechilds/docker-electrumx#56]
username@electrum:~/docker-electrumx$ sudo docker run lukechilds/electrumx
Generating a RSA private key
...........................................................+++++
...............................+++++
writing new private key to '/data/electrumx.key'
-----
INFO:electrumx:ElectrumX server starting
ERROR:electrumx:ElectrumX server terminated abnormally
Traceback (most recent call last):
  File "/electrumx/electrumx_server", line 31, in main
    env = Env()
  File "/electrumx/electrumx/server/env.py", line 44, in __init__
    self.daemon_url = self.required('DAEMON_URL')
  File "/electrumx/electrumx/lib/env_base.py", line 40, in required
    raise cls.Error('required envvar {} not set'.format(envvar))
electrumx.lib.env_base.EnvBase.Error: required envvar DAEMON_URL not set

**Comment by lukechilds** [comment]
The solution is in the output you pasted:

```
required envvar DAEMON_URL not set
```

You need to set `DAEMON_URL`, check the readme for an example.
