### ISSUE TITLE
"Error: RPC server failed to listen on localhost:8000"

### ISSUE THREAD

**Issue by JamesCropcho** [lukechilds/docker-electrumx#6]
Hello,

Thank you for a great Docker image.

Upon start-up, I get the following:

```
ERROR   RPC server failed to listen on localhost:8000 :[Errno 99] error while attempting to bind on address ('::1', 8000, 0, 0): address not available [controller.py:238]
```

If it matters, I am running `docker run` without any non-default `--net` or related arguments.

I cannot seem to remedy this. Has anyone else here encountered this, and found a fix?

Thanks,
James

**Comment by JamesCropcho** [comment]
Hello all,

I seem (?) to have fixed this, by appending to `docker run` the argument `--net=host`.

The error is no longer in the logs.

I don't understand why this would fix things, given that without the argument (i.e. running on the default `bridge` network), the container could bind on ports 50001–50002 without issue.

Does this seem like a sane fix?

Thanks,
James

**Comment by lukechilds** [comment]
I've never encountered that issue before, whats your host OS, Docker version etc?

**Comment by JamesCropcho** [comment]
Interesting. 

> `Docker version 17.12.0-ce`

```
$ cat /etc/system-release
Amazon Linux AMI release 2017.09
```

Hopefully that can help somehow.

From my end, all is pretty good right now. I seem to run everything fine, and without log errors.

**Comment by FMCorz** [comment]
I also experienced this issue and resorted to setting `RPC_HOST` to `127.0.0.1`.
