### ISSUE TITLE
Permission Errors

### ISSUE THREAD

**Issue by Rspigler** [lukechilds/docker-electrumx#8]
I am on a Fedora 28 machine.  I'm creating the container, as root:
```
docker run \
 -v /home/rspigler/electrumx:/data \
 -e DAEMON_URL=http://RPCUser:RPCPassword@localhost:8332 \
 -e COIN=BitcoinSegwit \
 -e ALLOW_ROOT=1 \
 -e BANNER_FILE=/home/rspigler/Documents/BannerFile.txt \
 -e ANON_LOGS=1 \
 -e MAX_SUBS=500000 \
 -e MAX_SESSION_SUBS=100000 \
 -e PEER_DISCOVERY=on \
 -e PEER_ANNOUNCE=1 \
 -e FORCE_PROXY=1 \
 -e TOR_PROXY_PORT=9050 \
 -e REPORT_HOST_TOR=l3e2obqp26fr2n5r.onion \
 -p 50002:50002 \
 lukechilds/electrumx
```
RPCUser and RPCPassword matches what's set in my `bitcoin.conf` file, and the onion address was generated by running `cat /var/lib/tor/electrum-service/hostname` after placing 

> HiddenServiceDir /var/lib/tor/electrum-service/
> HiddenServicePort 50002 127.0.0.1:50002

in my `Torrc` file and restarting Tor.

I get the following error:

> Generating a 2048 bit RSA private key
> ............................................+++
> ....................................................+++
> unable to write 'random state'
> writing new private key to '/data/electrumx.key'
> /data/electrumx.key: Permission denied
> 140254660733836:error:0200100D:system library:fopen:Permission >denied:bss_file.c:406:fopen('/data/electrumx.key','w')
> 140254660733836:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:408:
> INFO:root:ElectrumX server starting
> INFO:Controller:event loop policy: None
> INFO:Daemon:daemon #1 at localhost:8332/ (current)
> INFO:BlockProcessor:switching current directory to /data
> INFO:BlockProcessor:using leveldb for DB backend
> Traceback (most recent call last):
> File "/electrumx/electrumx_server.py", line 25, in main
>     controller = Controller(Env())
>   File "/electrumx/server/controller.py", line 84, in __init__
>     self.bp = self.coin.BLOCK_PROCESSOR(env, self, self.daemon)
>   File "/electrumx/server/block_processor.py", line 145, in __init__
>     super().__init__(env)
>   File "/electrumx/server/db.py", line 68, in __init__
>     self.open_dbs()
>   File "/electrumx/server/db.py", line 116, in open_dbs
>     self.utxo_db = self.db_class('utxo', for_sync)
>   File "/electrumx/server/storage.py", line 31, in __init__
>     self.open(name, create=self.is_new)
>   File "/electrumx/server/storage.py", line 83, in open
>     max_open_files=mof)
>   File "plyvel/_plyvel.pyx", line 247, in plyvel._plyvel.DB.__init__
>   File "plyvel/_plyvel.pyx", line 88, in plyvel._plyvel.raise_for_status
> plyvel._plyvel.IOError: b'IO error: utxo/LOCK: No such file or directory'
> CRITICAL:root:ElectrumX server terminated abnormally

Thank you for any help in advance.

**Comment by lukechilds** [comment]
Sounds like a permission error when trying to read/write to `/home/rspigler/electrumx`.

Can you try running the container as `rspigler` instead of `root`?

**Comment by lukechilds** [comment]
Also have you checked what the permissions are on `rspigler/electrumx`?

**Comment by Rspigler** [comment]
Yes, I can't even run `docker info` as `rspigler`.
Thanks, will do.  Just curious, why would running as `root` give me permission errors that running as a user would solve (I would think it's the other way around).

**Comment by lukechilds** [comment]
I don't think it would, I just don't think you should be running stuff as root 😉

Are you an an old version of Docker btw? I seem to remember there was an issue with old versions always having to run stuff as root.

**Comment by Rspigler** [comment]
(For future readers with similar problems - just follow the post install steps for linux https://docs.docker.com/install/linux/linux-postinstall/)

**Comment by lukechilds** [comment]
Is this resolved now?

Or are you still having filesystem permission issues?

**Comment by Rspigler** [comment]
No, unfortunately I get the same error when creating the container under `rspigler`

**Comment by lukechilds** [comment]
Hmmn, are you able to test on a different machine?

It sounds like a system specific issue.

**Comment by Rspigler** [comment]
Unfortunately, no, I am not.

However, I seem to have the found the issue, it seems its an SELinux problem.  In the short term, as an ugly hack I'm just disabling SELinux.  

`vim /etc/selinux/config` and set 

> SELINUX=disabled

and

> SELINUXTYPE=minimum

Then reboot.

Now, when creating the container (I removed `ALLOW_ROOT=1` since I'm running as `rspigler` now, but besides that I used all the same parameters as above) I get the output:

> Generating a 2048 bit RSA private key
.+++
.....+++
writing new private key to '/data/electrumx.key'
-----
INFO:root:ElectrumX server starting
INFO:Controller:event loop policy: None
INFO:Daemon:daemon #1 at localhost:8332/ (current)
INFO:BlockProcessor:switching current directory to /data
INFO:BlockProcessor:using leveldb for DB backend
INFO:BlockProcessor:created new database
INFO:BlockProcessor:creating metadata directory
INFO:BlockProcessor:software version: ElectrumX 1.4
INFO:BlockProcessor:supported protocol versions: 0.9-1.2
INFO:BlockProcessor:DB version: 6
INFO:BlockProcessor:coin: BitcoinSegwit
INFO:BlockProcessor:network: mainnet
INFO:BlockProcessor:height: -1
INFO:BlockProcessor:tip: 0000000000000000000000000000000000000000000000000000000000000000
INFO:BlockProcessor:tx count: 0
INFO:BlockProcessor:flush count: 0
INFO:BlockProcessor:sync time so far: 00s
INFO:BlockProcessor:reorg limit is 200 blocks
INFO:BlockProcessor:flushing DB cache at 1,200 MB
INFO:Controller:RPC server listening on localhost:8000
ERROR:Daemon:connection problem - is your daemon running?  Retrying occasionally...
ERROR:Daemon:connection problem - is your daemon running?  Retrying occasionally...

I added the following to my bitcoin.conf, even though I thought these were the defaults and not necessary, hoping it might solve the connection issues:

> rpcport=8332
rpcconnect=127.0.0.1

But then still get the same errors.

**Comment by Rspigler** [comment]
Hmm, why does the output read 

> Info:Controller:RPC server listening on localhost:8000

When my environment variable `DAEMON_URL` is set to `localhost:8332`, not `8000`?

**Comment by lukechilds** [comment]
>Hmm, why does the output read

> >Info:Controller:RPC server listening on localhost:8000

>When my environment variable DAEMON_URL is set to localhost:8332, not 8000?

That looks like ElectrumX's RPC server not your daemon.

`ALLOW_ROOT=1` is needed because the user inside the Docker container is root. However just removing this should be ok if you were setting it explicitly as it's set inside the image. Just don't override to 0.

**Comment by lukechilds** [comment]
Wait, do you have ElectrumX running inside Docker and the daemon running on your machine (not in Docker?)

If so it's might be a Docker network issue. You need to either give the Docker image first class access to your host network (not recommended). Or implement your daemon as a container and allow them to talk to each other with a tool like `docker-compose`. (recommended)

Example on how to do that here: https://github.com/lukechilds/docker-electrum-vertcoin/blob/master/docker-compose.yml

**Comment by Rspigler** [comment]
Thank you for all your help and time.

Yes exactly, I have ElectrumX running inside Docker and the daemon running on my own machine outside the Docker instance.

Is the first (unrecommended) option to run the Docker image as `docker run --net=host`?

Is there anyway to implement the second (recommended) option without just pulling Bitcoind as an image from someone else, but by building the image from my already verified and downloaded blockchain? For the obvious security assumptions, I'd like to download the reference client myself.

**Comment by Rspigler** [comment]
Building the container with `--net=host` and disabling `SELinux` has fixed this

**Comment by lukechilds** [comment]
>Is the first (unrecommended) option to run the Docker image as docker run --net=host?

Yep, as you found out 😉

But just be careful you're not exposing any ports you don't want to publicly, the image is no longer behind Dockers firewall.

>Is there anyway to implement the second (recommended) option without just pulling Bitcoind as an image from someone else, but by building the image from my already verified and downloaded blockchain? For the obvious security assumptions, I'd like to download the reference client myself.

Yep, just clone this repo and build the image yourself instead of pulling it from Docker Hub:

https://github.com/kylemanna/docker-bitcoind 

**Disclaimer:** I haven't audited that container, it was the first one that came up in my search.
